@startuml 订单管理

class TradeAggregate {
    - tradeId: TradeId
    - address: DeliveryAddress
    - customerId: UserId
    - merchantId: MerchantId
    - orders: Collection
}
class OrderAggregate {
    - orderId: OrderId
    - tradeId: TradeId
    - orderItems: Collection
    - state: SwitchState
}
class OrderItemAggregate {
    - orderItemId: OrderItemId
    - orderId: OrderId
    - tradeId: TradeId
    - state: SwitchState
}

class OrderAddress {
}

TradeAggregate "1"--*"*" OrderAggregate
OrderAggregate "1"--*"*" OrderItemAggregate

@enduml