@startuml 订单管理

class TradeAggregate {
    - tradeId: TradeId
    - address: DeliveryAddress
    - passwd: String
    - state: SwitchState
    - tenantId: TenantId
    - rolesJson: Text
'    - createdAt: Long
'    - updatedAt: Long
'    - createdBy: UserId
'    - updatedBy: UserId
    + inRole(RoleId id): Boolean
    + hasPermission(PermissionId id): Boolean
    + getRoles(): List
    + getPermissions(): List
}
class OrderAggregate {
    - orderId: OrderId
    - code: String
    - name: String
    - state: SwitchState
    - tenantId: TenantId
    - permsJson: Text
'    - createdAt: Long
'    - updatedAt: Long
'    - createdBy: UserId
'    - updatedBy: UserId
    + getUsers(): List
    + hasPermission(PermissionId id): Boolean
    + getPermissions(): List
}
class OrderItemAggregate {
    - orderItemId: OrderItemId
    - resourceId: ResourceId
    - operationId: OperationId
    - state: SwitchState
    - tenantId: TenantId
'    - createdAt: Long
'    - updatedAt: Long
'    - createdBy: UserId
'    - updatedBy: UserId
}
class Resource {
    - resourceId: ResourceId
    - code: String
    - name: String
    - state: SwitchState
    - parentId: ResourceId
    - tenantId: TenantId
'    - createdAt: Long
'    - updatedAt: Long
'    - createdBy: UserId
'    - updatedBy: UserId
}
class Operation {
    - operationId: OperationId
    - code: String
    - name: String
    - state: SwitchState
    - tenantId: TenantId
'    - createdAt: Long
'    - updatedAt: Long
'    - createdBy: UserId
'    - updatedBy: UserId
}

Organization --> Organization
UserAggregate "1"-->"*" Organization
UserAggregate "1"-->"*" RoleAggregate
RoleAggregate "1"-->"*" Permission
Permission *-->"1" Resource
Permission *-->"1" Operation

@enduml