@startuml

left to right direction

(交易) as trade
(订单) as order
(订单项) as orderItem
(日志系统) as Logger


(应用) as app
(资源位) as slot

note right of trade: 支撑子域
note right of order: 支撑子域
note right of orderItem: 支撑子域
note right of Logger: 通用子域


@enduml